version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./services/frontend:/app
    - /app/node_modules
    environment:
    - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
    - backend
    networks:
    - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
